ALTER TABLE "UploadedFile" ADD COLUMN "originalName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "UploadedFile" ADD COLUMN "extension" TEXT NOT NULL DEFAULT '';
ALTER TABLE "UploadedFile" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ImportJob" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE "ImportJob" ADD COLUMN "optionsJson" TEXT;
ALTER TABLE "ImportJob" ADD COLUMN "resultJson" TEXT;
ALTER TABLE "ImportJob" ADD COLUMN "completedAt" DATETIME;
ALTER TABLE "ImportJob" ADD COLUMN "appliedAt" DATETIME;

ALTER TABLE "ParseJob" ADD COLUMN "sourceTextPath" TEXT;
ALTER TABLE "ParseJob" ADD COLUMN "resultJson" TEXT;
ALTER TABLE "ParseJob" ADD COLUMN "confidence" REAL;
ALTER TABLE "ParseJob" ADD COLUMN "completedAt" DATETIME;
